"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"

type Language = "pt" | "en" | "fr" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("pt")

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language
    if (savedLang) {
      setLanguageState(savedLang)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

// Translations
const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navigation
    "nav.home": "Início",
    "nav.pricing": "Preços",
    "nav.docs": "Documentação",
    "nav.contact": "Contato",
    "nav.login": "Entrar",
    "nav.register": "Começar Grátis",
    
    // Hero Section
    "hero.badge": "Plataforma líder em gestão jurídica",
    "hero.title": "O futuro da gestão jurídica está aqui",
    "hero.subtitle": "Transforme seu escritório com a plataforma mais completa e intuitiva do mercado. Gestão de processos, clientes e finanças em um só lugar.",
    "hero.cta.primary": "Começar agora gratuitamente",
    "hero.cta.secondary": "Agendar demonstração",
    "hero.feature.no_card": "Sem cartão de crédito",
    "hero.feature.trial": "14 dias grátis",
    "hero.feature.cancel": "Cancele quando quiser",
    
    // Stats
    "stats.offices": "Escritórios ativos",
    "stats.cases": "Processos gerenciados",
    "stats.satisfaction": "Satisfação dos clientes",
    "stats.productivity": "Aumento de produtividade",
    
    // Features
    "features.badge": "Recursos",
    "features.title": "Tudo que você precisa em um só lugar",
    "features.subtitle": "Recursos poderosos para otimizar cada aspecto da sua prática jurídica",
    
    // Pricing
    "pricing.badge": "Preços",
    "pricing.title": "Planos para cada escritório",
    "pricing.subtitle": "Escolha o plano ideal para o seu negócio",
    "pricing.monthly": "Mensal",
    "pricing.semester": "Semestral",
    "pricing.annual": "Anual",
    "pricing.per_month": "/mês",
    "pricing.billed_monthly": "Faturado mensalmente",
    "pricing.billed_semester": "Faturado semestralmente",
    "pricing.billed_annual": "Faturado anualmente",
    "pricing.cta": "Começar agora",
    
    // Testimonials
    "testimonials.badge": "Depoimentos",
    "testimonials.title": "O que nossos clientes dizem",
    "testimonials.subtitle": "Escritórios de todo o Brasil confiam no Kamaia",
    
    // CTA
    "cta.title": "Pronto para transformar seu escritório?",
    "cta.subtitle": "Junte-se a centenas de escritórios que já modernizaram sua gestão jurídica",
    "cta.primary": "Começar teste gratuito",
    "cta.secondary": "Falar com vendas",
    
    // Footer
    "footer.product": "Produto",
    "footer.company": "Empresa",
    "footer.resources": "Recursos",
    "footer.legal": "Legal",
    "footer.newsletter": "Receba novidades",
    "footer.newsletter.placeholder": "seu@email.com",
    "footer.newsletter.cta": "Assinar",
    "footer.rights": "Todos os direitos reservados.",
    
    // Auth - Login
    "auth.login.title": "Acesse sua conta",
    "auth.login.subtitle": "Entre com suas credenciais para acessar o sistema",
    "auth.login.email": "Email",
    "auth.login.email.placeholder": "seu@email.com",
    "auth.login.password": "Senha",
    "auth.login.password.placeholder": "********",
    "auth.login.forgot": "Esqueceu a senha?",
    "auth.login.submit": "Entrar",
    "auth.login.no_account": "Não tem uma conta?",
    "auth.login.contact": "Entre em contacto",
    
    // Auth - Register
    "auth.register.title": "Criar uma conta",
    "auth.register.subtitle": "Preencha seus dados para se cadastrar",
    "auth.register.name": "Nome completo",
    "auth.register.name.placeholder": "João Silva",
    "auth.register.email": "Email",
    "auth.register.email.placeholder": "seu@email.com",
    "auth.register.password": "Senha",
    "auth.register.password.placeholder": "********",
    "auth.register.submit": "Criar conta",
    "auth.register.has_account": "Já tem uma conta?",
    "auth.register.login": "Fazer login",
    
    // Auth - Forgot Password
    "auth.forgot.title": "Esqueceu sua senha?",
    "auth.forgot.subtitle": "Insira seu email e enviaremos um link para redefinir sua senha",
    "auth.forgot.email": "Email",
    "auth.forgot.email.placeholder": "seu@email.com",
    "auth.forgot.submit": "Enviar link de recuperação",
    "auth.forgot.back": "Voltar para o login",
    "auth.forgot.success": "Email enviado!",
    "auth.forgot.success.description": "Verifique sua caixa de entrada para redefinir sua senha.",
    
    // Validation
    "validation.email.invalid": "Por favor, insira um email válido.",
    "validation.password.min": "A senha deve ter no mínimo 6 caracteres.",
    "validation.password.max": "A senha deve ter no máximo 50 caracteres.",
    "validation.password.uppercase": "A senha deve conter pelo menos uma letra maiúscula.",
    "validation.password.lowercase": "A senha deve conter pelo menos uma letra minúscula.",
    "validation.password.number": "A senha deve conter pelo menos um número.",
    "validation.name.min": "O nome deve ter no mínimo 2 caracteres.",

    // Public Pages - Home
    "home.hero.badge": "Plataforma líder em gestão jurídica",
    "home.hero.title": "O futuro da gestão jurídica está aqui",
    "home.hero.subtitle": "Transforme seu escritório com a plataforma mais completa e intuitiva do mercado. Gestão de processos, clientes e finanças em um só lugar.",
    "home.hero.cta.primary": "Começar agora gratuitamente",
    "home.hero.cta.secondary": "Agendar demonstração",
    "home.hero.trust.badge": "Sem cartão de crédito",
    "home.hero.trust.trial": "14 dias grátis",
    "home.hero.trust.cancel": "Cancele quando quiser",
    
    "home.stats.offices": "Escritórios ativos",
    "home.stats.cases": "Processos gerenciados",
    "home.stats.satisfaction": "Satisfação dos clientes",
    "home.stats.productivity": "Aumento de produtividade",
    
    "home.features.badge": "Recursos Poderosos",
    "home.features.title": "Tudo que você precisa em um só lugar",
    "home.features.subtitle": "Recursos poderosos projetados especificamente para escritórios de advocacia modernos",
    
    "home.testimonials.badge": "Depoimentos",
    "home.testimonials.title": "O que nossos clientes dizem",
    "home.testimonials.subtitle": "Escritórios de toda Angola e Mundo confiam na Kamaia",
    
    "home.cta.title": "Pronto para transformar seu escritório?",
    "home.cta.subtitle": "Junte-se a centenas de escritórios que já modernizaram sua gestão jurídica",
    "home.cta.primary": "Começar teste gratuito",
    "home.cta.secondary": "Falar com vendas",

    // Pricing Page
    "pricing.title": "Planos e Preços",
    "pricing.subtitle": "Escolha o plano ideal para o seu escritório",
    "pricing.monthly": "Mensal",
    "pricing.semester": "Semestral",
    "pricing.annual": "Anual",
    "pricing.per_month": "/mês",
    "pricing.popular": "Mais Popular",
    "pricing.cta": "Começar agora",
    "pricing.billed.monthly": "Faturado mensalmente",
    "pricing.billed.semester": "Faturado semestralmente",
    "pricing.billed.annual": "Faturado anualmente",
    "pricing.save": "Economize",
    "pricing.per_year": "por ano",
    "pricing.users": "usuários",
    "pricing.included": "Recursos incluídos:",
    "pricing.custom.title": "Precisa de uma solução personalizada?",
    "pricing.custom.description": "Para escritórios com necessidades específicas, oferecemos planos customizados com recursos exclusivos",
    "pricing.custom.cta": "Falar com especialista",
    "pricing.custom.docs": "Ver documentação",
    "pricing.features.title": "Recursos disponíveis em todos os planos",
    "pricing.features.subtitle": "Funcionalidades essenciais para sua gestão jurídica",
    "pricing.faq.title": "Perguntas Frequentes",
    "pricing.faq.subtitle": "Tudo o que você precisa saber sobre nossos planos",
    "pricing.faq.more": "Ainda tem dúvidas?",
    "pricing.faq.contact": "Entre em contato",

    // Footer
    "footer.description": "A plataforma mais completa para gestão de escritórios de advocacia e departamentos jurídicos.",
    "footer.newsletter.title": "Receba novidades",
    "footer.newsletter.placeholder": "seu@email.com",
    "footer.newsletter.button": "Assinar",
    "footer.product.title": "Produto",
    "footer.company.title": "Empresa",
    "footer.resources.title": "Recursos",
    "footer.legal.title": "Legal",
    "footer.contact.email": "Email",
    "footer.contact.phone": "Telefone",
    "footer.contact.address": "Endereço",
    "footer.copyright": "Todos os direitos reservados.",

    // Contact Page
    "contact.badge": "Entre em Contato",
    "contact.title": "Estamos aqui para ajudar",
    "contact.subtitle": "Fale com nossa equipe de especialistas e descubra como a Kamaia pode transformar seu escritório",
    "contact.info.email": "Email",
    "contact.info.email.value": "contato@kamaia.com",
    "contact.info.email.description": "Resposta em até 24 horas",
    "contact.info.phone": "Telefone",
    "contact.info.phone.value": "+244 949 273 453",
    "contact.info.phone.description": "Seg-Sex, 9h às 18h",
    "contact.info.address": "Endereço",
    "contact.info.address.value": "Luanda, Angola",
    "contact.info.address.description": "Av. Paulista, 1000",
    "contact.info.hours": "Horário",
    "contact.info.hours.value": "Segunda a Sexta",
    "contact.info.hours.description": "9h às 18h (BRT)",
    "contact.form.title": "Envie sua mensagem",
    "contact.form.subtitle": "Preencha o formulário abaixo e entraremos em contato em breve",
    "contact.form.name": "Nome completo",
    "contact.form.name.placeholder": "João Silva",
    "contact.form.email": "Email",
    "contact.form.email.placeholder": "joao@exemplo.com",
    "contact.form.phone": "Telefone",
    "contact.form.phone.placeholder": "+244 932938932",
    "contact.form.company": "Escritório/Empresa",
    "contact.form.company.placeholder": "Nome do escritório",
    "contact.form.subject": "Assunto",
    "contact.form.subject.placeholder": "Selecione um assunto",
    "contact.form.subject.sales": "Vendas e planos",
    "contact.form.subject.demo": "Agendar demonstração",
    "contact.form.subject.support": "Suporte técnico",
    "contact.form.subject.partnership": "Parcerias",
    "contact.form.subject.other": "Outro assunto",
    "contact.form.message": "Mensagem",
    "contact.form.message.placeholder": "Conte-nos como podemos ajudar...",
    "contact.form.submit": "Enviar mensagem",
    "contact.form.success.title": "Mensagem Enviada!",
    "contact.form.success.description": "Recebemos sua mensagem e retornaremos em breve.",
    "contact.reasons.title": "Como podemos ajudar?",
    "contact.reasons.product.title": "Dúvidas sobre o produto",
    "contact.reasons.product.description": "Tire suas dúvidas sobre funcionalidades e recursos",
    "contact.reasons.demo.title": "Agendar demonstração",
    "contact.reasons.demo.description": "Veja a Kamaia em ação com um especialista",
    "contact.reasons.support.title": "Suporte técnico",
    "contact.reasons.support.description": "Ajuda com problemas técnicos ou bugs",
    "contact.live.title": "Prefere falar ao vivo?",
    "contact.live.description": "Agende uma demonstração gratuita e veja a Kamaia em ação com um de nossos especialistas.",
    "contact.live.cta": "Agendar demonstração",
    "contact.help.title": "Central de ajuda",
    "contact.help.description": "Encontre respostas rápidas na nossa base de conhecimento",
    "contact.help.docs": "Documentação completa",
    "contact.help.faq": "Perguntas frequentes",
    "contact.help.videos": "Tutoriais em vídeo",
    "contact.help.api": "Documentação da API",
    "contact.office.title": "Nosso escritório",
    "contact.office.description": "Venha nos visitar pessoalmente",
    "contact.office.map": "Mapa do escritório",
    "contact.office.address": "Av. Paulista, 1000 - Luanda, Angola",
    "contact.validation.name.min": "Nome deve ter no mínimo 2 caracteres",
    "contact.validation.email.invalid": "Email inválido",
    "contact.validation.subject.required": "Selecione um assunto",
    "contact.validation.message.min": "Mensagem deve ter no mínimo 10 caracteres",
    "contact.toast.success": "Mensagem enviada com sucesso!",
    "contact.toast.description": "Retornaremos em breve.",

    // Home Page - Pricing Section (não traduzido)
    "home.pricing.badge": "Preços",
    "home.pricing.title": "Planos para cada escritório",
    "home.pricing.subtitle": "Escolha o plano ideal para o seu negócio",
    "home.pricing.monthly": "Mensal",
    "home.pricing.semester": "Semestral",
    "home.pricing.annual": "Anual",
    "home.pricing.save.semester": "-10%",
    "home.pricing.save.annual": "-20%",
    "home.pricing.popular": "Mais popular",
    "home.pricing.billed.monthly": "Faturado mensalmente",
    "home.pricing.billed.semester": "Faturado semestralmente",
    "home.pricing.billed.annual": "Faturado anualmente",
    "home.pricing.cta": "Começar agora",
    "home.pricing.plan.starter.name": "Starter",
    "home.pricing.plan.starter.description": "Perfeito para escritórios iniciantes",
    "home.pricing.plan.professional.name": "Professional",
    "home.pricing.plan.professional.description": "Para escritórios em crescimento",
    "home.pricing.plan.enterprise.name": "Enterprise",
    "home.pricing.plan.enterprise.description": "Para grandes escritórios",

    // Pricing Page - Plans Details
    "pricing.plan.starter.name": "Starter",
    "pricing.plan.starter.description": "Perfeito para escritórios iniciantes",
    "pricing.plan.professional.name": "Professional",
    "pricing.plan.professional.description": "Para escritórios em crescimento",
    "pricing.plan.enterprise.name": "Enterprise",
    "pricing.plan.enterprise.description": "Para grandes escritórios",
    "pricing.feature.users": "Até {count} usuários",
    "pricing.feature.users.unlimited": "Usuários ilimitados",
    "pricing.feature.process.basic": "Gestão de processos básica",
    "pricing.feature.process.complete": "Gestão completa de processos",
    "pricing.feature.process.all": "Todos os recursos Professional",
    "pricing.feature.storage": "{size} de armazenamento",
    "pricing.feature.storage.unlimited": "Armazenamento ilimitado",
    "pricing.feature.support.email": "Suporte por email",
    "pricing.feature.support.priority": "Suporte prioritário 24/7",
    "pricing.feature.support.phone": "Suporte telefônico premium",
    "pricing.feature.reports.basic": "Relatórios básicos",
    "pricing.feature.reports.advanced": "Relatórios avançados",
    "pricing.feature.integrations": "Integrações via API",
    "pricing.feature.integrations.custom": "Integrações customizadas",
    "pricing.feature.agenda.simple": "Agenda simples",
    "pricing.feature.agenda.smart": "Agenda inteligente",
    "pricing.feature.documents": "Gestão de documentos",
    "pricing.feature.dashboard.basic": "Dashboard básico",
    "pricing.feature.dashboard.custom": "Dashboard personalizado",
    "pricing.feature.automation": "Automação de tarefas",
    "pricing.feature.notifications": "Notificações em tempo real",
    "pricing.feature.finance": "Controle financeiro completo",
    "pricing.feature.backup": "Backup automático diário",
    "pricing.feature.manager": "Gerente de conta dedicado",
    "pricing.feature.training": "Treinamento personalizado",
    "pricing.feature.sla": "SLA garantido 99.9%",
    "pricing.feature.whitelabel": "White-label disponível",
    "pricing.feature.audit": "Auditoria e compliance",
    "pricing.feature.migration": "Migração de dados assistida",
    "pricing.feature.consulting": "Consultoria estratégica",
    "pricing.features.multiuser.title": "Multi-usuário",
    "pricing.features.multiuser.description": "Gestão de equipes com controle de permissões",
    "pricing.features.security.title": "Segurança",
    "pricing.features.security.description": "Criptografia e conformidade com LGPD",
    "pricing.features.performance.title": "Performance",
    "pricing.features.performance.description": "Sistema rápido e responsivo",
    "pricing.features.storage.title": "Armazenamento",
    "pricing.features.storage.description": "Cloud seguro e escalável",
    "pricing.features.support.title": "Suporte",
    "pricing.features.support.description": "Equipe especializada sempre disponível",
    "pricing.features.analytics.title": "Analytics",
    "pricing.features.analytics.description": "Relatórios e insights avançados",
    "pricing.faq.change_plan": "Posso mudar de plano a qualquer momento?",
    "pricing.faq.change_plan.answer": "Sim! Você pode fazer upgrade ou downgrade do seu plano a qualquer momento. As alterações entram em vigor no próximo ciclo de faturamento.",
    "pricing.faq.trial": "Existe período de teste gratuito?",
    "pricing.faq.trial.answer": "Sim, oferecemos 14 dias de teste gratuito em todos os planos, sem necessidade de cartão de crédito.",
    "pricing.faq.cancel": "Como funciona o cancelamento?",
    "pricing.faq.cancel.answer": "Você pode cancelar sua assinatura a qualquer momento sem multas ou taxas adicionais. Seus dados ficam disponíveis por 30 dias após o cancelamento.",
    "pricing.faq.ngo": "Vocês oferecem desconto para ONGs?",
    "pricing.faq.ngo.answer": "Sim! Oferecemos descontos especiais para organizações sem fins lucrativos. Entre em contato com nossa equipe comercial.",
    "pricing.faq.support_included": "Os preços incluem suporte técnico?",
    "pricing.faq.support_included.answer": "Sim, todos os planos incluem suporte técnico. O nível de suporte varia conforme o plano escolhido.",
    "pricing.faq.setup_fee": "Há taxa de setup ou instalação?",
    "pricing.faq.setup_fee.answer": "Não, não cobramos nenhuma taxa de setup. Você paga apenas a mensalidade do plano escolhido.",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.pricing": "Pricing",
    "nav.docs": "Documentation",
    "nav.contact": "Contact",
    "nav.login": "Sign In",
    "nav.register": "Get Started",
    
    // Hero Section
    "hero.badge": "Leading legal management platform",
    "hero.title": "The future of legal management is here",
    "hero.subtitle": "Transform your firm with the most complete and intuitive platform on the market. Process, client and financial management all in one place.",
    "hero.cta.primary": "Start now for free",
    "hero.cta.secondary": "Schedule demo",
    "hero.feature.no_card": "No credit card required",
    "hero.feature.trial": "14 days free",
    "hero.feature.cancel": "Cancel anytime",
    
    // Stats
    "stats.offices": "Active offices",
    "stats.cases": "Cases managed",
    "stats.satisfaction": "Customer satisfaction",
    "stats.productivity": "Productivity increase",
    
    // Features
    "features.badge": "Features",
    "features.title": "Everything you need in one place",
    "features.subtitle": "Powerful features to optimize every aspect of your legal practice",
    
    // Pricing
    "pricing.badge": "Pricing",
    "pricing.title": "Plans for every firm",
    "pricing.subtitle": "Choose the ideal plan for your business",
    "pricing.monthly": "Monthly",
    "pricing.semester": "Semester",
    "pricing.annual": "Annual",
    "pricing.per_month": "/month",
    "pricing.billed_monthly": "Billed monthly",
    "pricing.billed_semester": "Billed every six months",
    "pricing.billed_annual": "Billed annually",
    "pricing.cta": "Get started",
    
    // Testimonials
    "testimonials.badge": "Testimonials",
    "testimonials.title": "What our clients say",
    "testimonials.subtitle": "Law firms across Brazil trust Kamaia",
    
    // CTA
    "cta.title": "Ready to transform your firm?",
    "cta.subtitle": "Join hundreds of firms that have already modernized their legal management",
    "cta.primary": "Start free trial",
    "cta.secondary": "Talk to sales",
    
    // Footer
    "footer.product": "Product",
    "footer.company": "Company",
    "footer.resources": "Resources",
    "footer.legal": "Legal",
    "footer.newsletter": "Get updates",
    "footer.newsletter.placeholder": "your@email.com",
    "footer.newsletter.cta": "Subscribe",
    "footer.rights": "All rights reserved.",
    
    // Auth - Login
    "auth.login.title": "Access your account",
    "auth.login.subtitle": "Enter your credentials to access the system",
    "auth.login.email": "Email",
    "auth.login.email.placeholder": "your@email.com",
    "auth.login.password": "Password",
    "auth.login.password.placeholder": "********",
    "auth.login.forgot": "Forgot password?",
    "auth.login.submit": "Sign In",
    "auth.login.no_account": "Don't have an account?",
    "auth.login.contact": "Get in touch",
    
    // Auth - Register
    "auth.register.title": "Create an account",
    "auth.register.subtitle": "Fill in your details to register",
    "auth.register.name": "Full name",
    "auth.register.name.placeholder": "John Doe",
    "auth.register.email": "Email",
    "auth.register.email.placeholder": "your@email.com",
    "auth.register.password": "Password",
    "auth.register.password.placeholder": "********",
    "auth.register.submit": "Create account",
    "auth.register.has_account": "Already have an account?",
    "auth.register.login": "Sign in",
    
    // Auth - Forgot Password
    "auth.forgot.title": "Forgot your password?",
    "auth.forgot.subtitle": "Enter your email and we'll send you a reset link",
    "auth.forgot.email": "Email",
    "auth.forgot.email.placeholder": "your@email.com",
    "auth.forgot.submit": "Send recovery link",
    "auth.forgot.back": "Back to login",
    "auth.forgot.success": "Email sent!",
    "auth.forgot.success.description": "Check your inbox to reset your password.",
    
    // Validation
    "validation.email.invalid": "Please enter a valid email.",
    "validation.password.min": "Password must be at least 6 characters.",
    "validation.password.max": "Password must be at most 50 characters.",
    "validation.password.uppercase": "Password must contain at least one uppercase letter.",
    "validation.password.lowercase": "Password must contain at least one lowercase letter.",
    "validation.password.number": "Password must contain at least one number.",
    "validation.name.min": "Name must be at least 2 characters.",

    // Public Pages - Home
    "home.hero.badge": "Leading legal management platform",
    "home.hero.title": "The future of legal management is here",
    "home.hero.subtitle": "Transform your firm with the most complete and intuitive platform on the market. Process, client and financial management all in one place.",
    "home.hero.cta.primary": "Start now for free",
    "home.hero.cta.secondary": "Schedule demo",
    "home.hero.trust.badge": "No credit card required",
    "home.hero.trust.trial": "14 days free",
    "home.hero.trust.cancel": "Cancel anytime",
    
    "home.stats.offices": "Active offices",
    "home.stats.cases": "Cases managed",
    "home.stats.satisfaction": "Customer satisfaction",
    "home.stats.productivity": "Productivity increase",
    
    "home.features.badge": "Powerful Features",
    "home.features.title": "Everything you need in one place",
    "home.features.subtitle": "Powerful features designed specifically for modern law firms",
    
    "home.testimonials.badge": "Testimonials",
    "home.testimonials.title": "What our clients say",
    "home.testimonials.subtitle": "Law firms across Angola and the World trust Kamaia",
    
    "home.cta.title": "Ready to transform your firm?",
    "home.cta.subtitle": "Join hundreds of firms that have already modernized their legal management",
    "home.cta.primary": "Start free trial",
    "home.cta.secondary": "Talk to sales",

    // Pricing Page
    "pricing.title": "Plans and Pricing",
    "pricing.subtitle": "Choose the ideal plan for your firm",
    "pricing.monthly": "Monthly",
    "pricing.semester": "Semester",
    "pricing.annual": "Annual",
    "pricing.per_month": "/month",
    "pricing.popular": "Most Popular",
    "pricing.cta": "Get started",
    "pricing.billed.monthly": "Billed monthly",
    "pricing.billed.semester": "Billed every six months",
    "pricing.billed.annual": "Billed annually",
    "pricing.save": "Save",
    "pricing.per_year": "per year",
    "pricing.users": "users",
    "pricing.included": "Included features:",
    "pricing.custom.title": "Need a custom solution?",
    "pricing.custom.description": "For firms with specific needs, we offer customized plans with exclusive features",
    "pricing.custom.cta": "Talk to specialist",
    "pricing.custom.docs": "View documentation",
    "pricing.features.title": "Features available in all plans",
    "pricing.features.subtitle": "Essential features for your legal management",
    "pricing.faq.title": "Frequently Asked Questions",
    "pricing.faq.subtitle": "Everything you need to know about our plans",
    "pricing.faq.more": "Still have questions?",
    "pricing.faq.contact": "Get in touch",

    // Footer
    "footer.description": "The most complete platform for managing law firms and legal departments.",
    "footer.newsletter.title": "Get updates",
    "footer.newsletter.placeholder": "your@email.com",
    "footer.newsletter.button": "Subscribe",
    "footer.product.title": "Product",
    "footer.company.title": "Company",
    "footer.resources.title": "Resources",
    "footer.legal.title": "Legal",
    "footer.contact.email": "Email",
    "footer.contact.phone": "Phone",
    "footer.contact.address": "Address",
    "footer.copyright": "All rights reserved.",

    // Contact Page
    "contact.badge": "Get in Touch",
    "contact.title": "We're here to help",
    "contact.subtitle": "Talk to our team of experts and discover how Kamaia can transform your firm",
    "contact.info.email": "Email",
    "contact.info.email.value": "contact@kamaia.com",
    "contact.info.email.description": "Response within 24 hours",
    "contact.info.phone": "Phone",
    "contact.info.phone.value": "+244 949 273 453",
    "contact.info.phone.description": "Mon-Fri, 9am to 6pm",
    "contact.info.address": "Address",
    "contact.info.address.value": "Luanda, Angola",
    "contact.info.address.description": "Av. Paulista, 1000",
    "contact.info.hours": "Hours",
    "contact.info.hours.value": "Monday to Friday",
    "contact.info.hours.description": "9am to 6pm (BRT)",
    "contact.form.title": "Send your message",
    "contact.form.subtitle": "Fill out the form below and we'll get back to you soon",
    "contact.form.name": "Full name",
    "contact.form.name.placeholder": "John Doe",
    "contact.form.email": "Email",
    "contact.form.email.placeholder": "john@example.com",
    "contact.form.phone": "Phone",
    "contact.form.phone.placeholder": "+244 932938932",
    "contact.form.company": "Firm/Company",
    "contact.form.company.placeholder": "Firm name",
    "contact.form.subject": "Subject",
    "contact.form.subject.placeholder": "Select a subject",
    "contact.form.subject.sales": "Sales and plans",
    "contact.form.subject.demo": "Schedule demo",
    "contact.form.subject.support": "Technical support",
    "contact.form.subject.partnership": "Partnerships",
    "contact.form.subject.other": "Other subject",
    "contact.form.message": "Message",
    "contact.form.message.placeholder": "Tell us how we can help...",
    "contact.form.submit": "Send message",
    "contact.form.success.title": "Message Sent!",
    "contact.form.success.description": "We've received your message and will get back to you soon.",
    "contact.reasons.title": "How can we help?",
    "contact.reasons.product.title": "Product questions",
    "contact.reasons.product.description": "Learn about features and functionalities",
    "contact.reasons.demo.title": "Schedule demo",
    "contact.reasons.demo.description": "See Kamaia in action with a specialist",
    "contact.reasons.support.title": "Technical support",
    "contact.reasons.support.description": "Help with technical issues or bugs",
    "contact.live.title": "Prefer to talk live?",
    "contact.live.description": "Schedule a free demo and see Kamaia in action with one of our specialists.",
    "contact.live.cta": "Schedule demo",
    "contact.help.title": "Help center",
    "contact.help.description": "Find quick answers in our knowledge base",
    "contact.help.docs": "Complete documentation",
    "contact.help.faq": "Frequently asked questions",
    "contact.help.videos": "Video tutorials",
    "contact.help.api": "API documentation",
    "contact.office.title": "Our office",
    "contact.office.description": "Come visit us in person",
    "contact.office.map": "Office map",
    "contact.office.address": "Av. Paulista, 1000 - Luanda, Angola",
    "contact.validation.name.min": "Name must be at least 2 characters",
    "contact.validation.email.invalid": "Invalid email",
    "contact.validation.subject.required": "Select a subject",
    "contact.validation.message.min": "Message must be at least 10 characters",
    "contact.toast.success": "Message sent successfully!",
    "contact.toast.description": "We'll get back to you soon.",

    // Home Page - Pricing Section
    "home.pricing.badge": "Pricing",
    "home.pricing.title": "Plans for every firm",
    "home.pricing.subtitle": "Choose the ideal plan for your business",
    "home.pricing.monthly": "Monthly",
    "home.pricing.semester": "Semester",
    "home.pricing.annual": "Annual",
    "home.pricing.save.semester": "-10%",
    "home.pricing.save.annual": "-20%",
    "home.pricing.popular": "Most popular",
    "home.pricing.billed.monthly": "Billed monthly",
    "home.pricing.billed.semester": "Billed every six months",
    "home.pricing.billed.annual": "Billed annually",
    "home.pricing.cta": "Get started",
    "home.pricing.plan.starter.name": "Starter",
    "home.pricing.plan.starter.description": "Perfect for starting firms",
    "home.pricing.plan.professional.name": "Professional",
    "home.pricing.plan.professional.description": "For growing firms",
    "home.pricing.plan.enterprise.name": "Enterprise",
    "home.pricing.plan.enterprise.description": "For large firms",

    // Pricing Page - Plans Details
    "pricing.plan.starter.name": "Starter",
    "pricing.plan.starter.description": "Perfect for starting firms",
    "pricing.plan.professional.name": "Professional",
    "pricing.plan.professional.description": "For growing firms",
    "pricing.plan.enterprise.name": "Enterprise",
    "pricing.plan.enterprise.description": "For large firms",
    "pricing.feature.users": "Up to {count} users",
    "pricing.feature.users.unlimited": "Unlimited users",
    "pricing.feature.process.basic": "Basic case management",
    "pricing.feature.process.complete": "Complete case management",
    "pricing.feature.process.all": "All Professional features",
    "pricing.feature.storage": "{size} storage",
    "pricing.feature.storage.unlimited": "Unlimited storage",
    "pricing.feature.support.email": "Email support",
    "pricing.feature.support.priority": "Priority 24/7 support",
    "pricing.feature.support.phone": "Premium phone support",
    "pricing.feature.reports.basic": "Basic reports",
    "pricing.feature.reports.advanced": "Advanced reports",
    "pricing.feature.integrations": "API integrations",
    "pricing.feature.integrations.custom": "Custom integrations",
    "pricing.feature.agenda.simple": "Simple calendar",
    "pricing.feature.agenda.smart": "Smart calendar",
    "pricing.feature.documents": "Document management",
    "pricing.feature.dashboard.basic": "Basic dashboard",
    "pricing.feature.dashboard.custom": "Custom dashboard",
    "pricing.feature.automation": "Task automation",
    "pricing.feature.notifications": "Real-time notifications",
    "pricing.feature.finance": "Complete financial control",
    "pricing.feature.backup": "Daily automatic backup",
    "pricing.feature.manager": "Dedicated account manager",
    "pricing.feature.training": "Personalized training",
    "pricing.feature.sla": "99.9% SLA guaranteed",
    "pricing.feature.whitelabel": "White-label available",
    "pricing.feature.audit": "Audit and compliance",
    "pricing.feature.migration": "Assisted data migration",
    "pricing.feature.consulting": "Strategic consulting",
    "pricing.features.multiuser.title": "Multi-user",
    "pricing.features.multiuser.description": "Team management with permission control",
    "pricing.features.security.title": "Security",
    "pricing.features.security.description": "Encryption and LGPD compliance",
    "pricing.features.performance.title": "Performance",
    "pricing.features.performance.description": "Fast and responsive system",
    "pricing.features.storage.title": "Storage",
    "pricing.features.storage.description": "Secure and scalable cloud",
    "pricing.features.support.title": "Support",
    "pricing.features.support.description": "Specialized team always available",
    "pricing.features.analytics.title": "Analytics",
    "pricing.features.analytics.description": "Advanced reports and insights",
    "pricing.faq.change_plan": "Can I change plans anytime?",
    "pricing.faq.change_plan.answer": "Yes! You can upgrade or downgrade your plan at any time. Changes take effect in the next billing cycle.",
    "pricing.faq.trial": "Is there a free trial period?",
    "pricing.faq.trial.answer": "Yes, we offer a 14-day free trial on all plans, no credit card required.",
    "pricing.faq.cancel": "How does cancellation work?",
    "pricing.faq.cancel.answer": "You can cancel your subscription at any time without penalties or additional fees. Your data remains available for 30 days after cancellation.",
    "pricing.faq.ngo": "Do you offer discounts for NGOs?",
    "pricing.faq.ngo.answer": "Yes! We offer special discounts for non-profit organizations. Contact our sales team.",
    "pricing.faq.support_included": "Do prices include technical support?",
    "pricing.faq.support_included.answer": "Yes, all plans include technical support. The level of support varies according to the chosen plan.",
    "pricing.faq.setup_fee": "Is there a setup or installation fee?",
    "pricing.faq.setup_fee.answer": "No, we don't charge any setup fees. You only pay the monthly fee for the chosen plan.",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.pricing": "Tarifs",
    "nav.docs": "Documentation",
    "nav.contact": "Contact",
    "nav.login": "Se connecter",
    "nav.register": "Commencer",
    
    // Hero Section
    "hero.badge": "Plateforme leader en gestion juridique",
    "hero.title": "L'avenir de la gestion juridique est ici",
    "hero.subtitle": "Transformez votre cabinet avec la plateforme la plus complète et intuitive du marché. Gestion des dossiers, clients et finances en un seul endroit.",
    "hero.cta.primary": "Commencer gratuitement",
    "hero.cta.secondary": "Planifier une démo",
    "hero.feature.no_card": "Sans carte de crédit",
    "hero.feature.trial": "14 jours gratuits",
    "hero.feature.cancel": "Annuler à tout moment",
    
    // Stats
    "stats.offices": "Cabinets actifs",
    "stats.cases": "Dossiers gérés",
    "stats.satisfaction": "Satisfaction client",
    "stats.productivity": "Augmentation de productivité",
    
    // Features
    "features.badge": "Fonctionnalités",
    "features.title": "Tout ce dont vous avez besoin en un seul endroit",
    "features.subtitle": "Des fonctionnalités puissantes pour optimiser chaque aspect de votre pratique juridique",
    
    // Pricing
    "pricing.badge": "Tarifs",
    "pricing.title": "Plans pour chaque cabinet",
    "pricing.subtitle": "Choisissez le plan idéal pour votre entreprise",
    "pricing.monthly": "Mensuel",
    "pricing.semester": "Semestriel",
    "pricing.annual": "Annuel",
    "pricing.per_month": "/mois",
    "pricing.billed_monthly": "Facturé mensuellement",
    "pricing.billed_semester": "Facturé semestriellement",
    "pricing.billed_annual": "Facturé annuellement",
    "pricing.cta": "Commencer",
    
    // Testimonials
    "testimonials.badge": "Témoignages",
    "testimonials.title": "Ce que disent nos clients",
    "testimonials.subtitle": "Des cabinets à travers le Brésil font confiance à Kamaia",
    
    // CTA
    "cta.title": "Prêt à transformer votre cabinet?",
    "cta.subtitle": "Rejoignez des centaines de cabinets qui ont déjà modernisé leur gestion juridique",
    "cta.primary": "Commencer l'essai gratuit",
    "cta.secondary": "Parler aux ventes",
    
    // Footer
    "footer.product": "Produit",
    "footer.company": "Entreprise",
    "footer.resources": "Ressources",
    "footer.legal": "Légal",
    "footer.newsletter": "Recevoir des nouvelles",
    "footer.newsletter.placeholder": "votre@email.com",
    "footer.newsletter.cta": "S'abonner",
    "footer.rights": "Tous droits réservés.",
    
    // Auth - Login
    "auth.login.title": "Accédez à votre compte",
    "auth.login.subtitle": "Entrez vos identifiants pour accéder au système",
    "auth.login.email": "Email",
    "auth.login.email.placeholder": "votre@email.com",
    "auth.login.password": "Mot de passe",
    "auth.login.password.placeholder": "********",
    "auth.login.forgot": "Mot de passe oublié?",
    "auth.login.submit": "Se connecter",
    "auth.login.no_account": "Vous n'avez pas de compte?",
    "auth.login.contact": "Contactez-nous",
    
    // Auth - Register
    "auth.register.title": "Créer un compte",
    "auth.register.subtitle": "Remplissez vos informations pour vous inscrire",
    "auth.register.name": "Nom complet",
    "auth.register.name.placeholder": "Jean Dupont",
    "auth.register.email": "Email",
    "auth.register.email.placeholder": "votre@email.com",
    "auth.register.password": "Mot de passe",
    "auth.register.password.placeholder": "********",
    "auth.register.submit": "Créer un compte",
    "auth.register.has_account": "Vous avez déjà un compte?",
    "auth.register.login": "Se connecter",
    
    // Auth - Forgot Password
    "auth.forgot.title": "Mot de passe oublié?",
    "auth.forgot.subtitle": "Entrez votre email et nous vous enverrons un lien de réinitialisation",
    "auth.forgot.email": "Email",
    "auth.forgot.email.placeholder": "votre@email.com",
    "auth.forgot.submit": "Envoyer le lien de récupération",
    "auth.forgot.back": "Retour à la connexion",
    "auth.forgot.success": "Email envoyé!",
    "auth.forgot.success.description": "Vérifiez votre boîte de réception pour réinitialiser votre mot de passe.",
    
    // Validation
    "validation.email.invalid": "Veuillez entrer un email valide.",
    "validation.password.min": "Le mot de passe doit contenir au moins 6 caractères.",
    "validation.password.max": "Le mot de passe doit contenir au maximum 50 caractères.",
    "validation.password.uppercase": "Le mot de passe doit contenir au moins une lettre majuscule.",
    "validation.password.lowercase": "Le mot de passe doit contenir au moins une lettre minuscule.",
    "validation.password.number": "Le mot de passe doit contenir au moins un chiffre.",
    "validation.name.min": "Le nom doit contenir au moins 2 caractères.",

    // Public Pages - Home
    "home.hero.badge": "Plateforme leader en gestion juridique",
    "home.hero.title": "L'avenir de la gestion juridique est ici",
    "home.hero.subtitle": "Transformez votre cabinet avec la plateforme la plus complète et intuitive du marché. Gestion des dossiers, clients et finances en un seul endroit.",
    "home.hero.cta.primary": "Commencer gratuitement",
    "home.hero.cta.secondary": "Planifier une démo",
    "home.hero.trust.badge": "Sans carte de crédit",
    "home.hero.trust.trial": "14 jours gratuits",
    "home.hero.trust.cancel": "Annuler à tout moment",
    
    "home.stats.offices": "Cabinets actifs",
    "home.stats.cases": "Dossiers gérés",
    "home.stats.satisfaction": "Satisfaction client",
    "home.stats.productivity": "Augmentation de productivité",
    
    "home.features.badge": "Fonctionnalités Puissantes",
    "home.features.title": "Tout ce dont vous avez besoin en un seul endroit",
    "home.features.subtitle": "Des fonctionnalités puissantes conçues spécifiquement pour les cabinets d'avocats modernes",
    
    "home.testimonials.badge": "Témoignages",
    "home.testimonials.title": "Ce que disent nos clients",
    "home.testimonials.subtitle": "Des cabinets à travers l'Angola et le Monde font confiance à Kamaia",
    
    "home.cta.title": "Prêt à transformer votre cabinet?",
    "home.cta.subtitle": "Rejoignez des centaines de cabinets qui ont déjà modernisé leur gestion juridique",
    "home.cta.primary": "Commencer l'essai gratuit",
    "home.cta.secondary": "Parler aux ventes",

    // Pricing Page
    "pricing.title": "Plans et Tarifs",
    "pricing.subtitle": "Choisissez le plan idéal pour votre cabinet",
    "pricing.monthly": "Mensuel",
    "pricing.semester": "Semestriel",
    "pricing.annual": "Annuel",
    "pricing.per_month": "/mois",
    "pricing.popular": "Le Plus Populaire",
    "pricing.cta": "Commencer",
    "pricing.billed.monthly": "Facturé mensuellement",
    "pricing.billed.semester": "Facturé semestriellement",
    "pricing.billed.annual": "Facturé annuellement",
    "pricing.save": "Économisez",
    "pricing.per_year": "par an",
    "pricing.users": "utilisateurs",
    "pricing.included": "Fonctionnalités incluses:",
    "pricing.custom.title": "Besoin d'une solution personnalisée?",
    "pricing.custom.description": "Pour les cabinets avec des besoins spécifiques, nous offrons des plans personnalisés avec des fonctionnalités exclusives",
    "pricing.custom.cta": "Parler à un spécialiste",
    "pricing.custom.docs": "Voir la documentation",
    "pricing.features.title": "Fonctionnalités disponibles dans tous les plans",
    "pricing.features.subtitle": "Fonctionnalités essentielles pour votre gestion juridique",
    "pricing.faq.title": "Questions Fréquemment Posées",
    "pricing.faq.subtitle": "Tout ce que vous devez savoir sur nos plans",
    "pricing.faq.more": "Vous avez encore des questions?",
    "pricing.faq.contact": "Contactez-nous",

    // Footer
    "footer.description": "La plateforme la plus complète pour la gestion des cabinets d'avocats et des départements juridiques.",
    "footer.newsletter.title": "Recevoir des nouvelles",
    "footer.newsletter.placeholder": "votre@email.com",
    "footer.newsletter.button": "S'abonner",
    "footer.product.title": "Produit",
    "footer.company.title": "Entreprise",
    "footer.resources.title": "Ressources",
    "footer.legal.title": "Légal",
    "footer.contact.email": "Email",
    "footer.contact.phone": "Téléphone",
    "footer.contact.address": "Adresse",
    "footer.copyright": "Tous droits réservés.",

    // Contact Page
    "contact.badge": "Contactez-nous",
    "contact.title": "Nous sommes là pour vous aider",
    "contact.subtitle": "Parlez à notre équipe d'experts et découvrez comment Kamaia peut transformer votre cabinet",
    "contact.info.email": "Email",
    "contact.info.email.value": "contact@kamaia.com",
    "contact.info.email.description": "Réponse sous 24 heures",
    "contact.info.phone": "Téléphone",
    "contact.info.phone.value": "+244 949 273 453",
    "contact.info.phone.description": "Lun-Ven, 9h à 18h",
    "contact.info.address": "Adresse",
    "contact.info.address.value": "Luanda, Angola",
    "contact.info.address.description": "Av. Paulista, 1000",
    "contact.info.hours": "Horaires",
    "contact.info.hours.value": "Lundi à Vendredi",
    "contact.info.hours.description": "9h à 18h (BRT)",
    "contact.form.title": "Envoyez votre message",
    "contact.form.subtitle": "Remplissez le formulaire ci-dessous et nous vous répondrons bientôt",
    "contact.form.name": "Nom complet",
    "contact.form.name.placeholder": "Jean Dupont",
    "contact.form.email": "Email",
    "contact.form.email.placeholder": "jean@exemple.com",
    "contact.form.phone": "Téléphone",
    "contact.form.phone.placeholder": "+244 932938932",
    "contact.form.company": "Cabinet/Entreprise",
    "contact.form.company.placeholder": "Nom du cabinet",
    "contact.form.subject": "Sujet",
    "contact.form.subject.placeholder": "Sélectionnez un sujet",
    "contact.form.subject.sales": "Ventes et plans",
    "contact.form.subject.demo": "Planifier une démo",
    "contact.form.subject.support": "Support technique",
    "contact.form.subject.partnership": "Partenariats",
    "contact.form.subject.other": "Autre sujet",
    "contact.form.message": "Message",
    "contact.form.message.placeholder": "Dites-nous comment nous pouvons vous aider...",
    "contact.form.submit": "Envoyer le message",
    "contact.form.success.title": "Message Envoyé!",
    "contact.form.success.description": "Nous avons reçu votre message et vous répondrons bientôt.",
    "contact.reasons.title": "Comment pouvons-nous vous aider?",
    "contact.reasons.product.title": "Questions sur le produit",
    "contact.reasons.product.description": "En savoir plus sur les fonctionnalités et les ressources",
    "contact.reasons.demo.title": "Planifier une démo",
    "contact.reasons.demo.description": "Voyez Kamaia en action avec un spécialiste",
    "contact.reasons.support.title": "Support technique",
    "contact.reasons.support.description": "Aide pour les problèmes techniques ou bugs",
    "contact.live.title": "Préférez parler en direct?",
    "contact.live.description": "Planifiez une démo gratuite et voyez Kamaia en action avec l'un de nos spécialistes.",
    "contact.live.cta": "Planifier une démo",
    "contact.help.title": "Centre d'aide",
    "contact.help.description": "Trouvez des réponses rapides dans notre base de connaissances",
    "contact.help.docs": "Documentation complète",
    "contact.help.faq": "Questions fréquemment posées",
    "contact.help.videos": "Tutoriels vidéo",
    "contact.help.api": "Documentation de l'API",
    "contact.office.title": "Notre bureau",
    "contact.office.description": "Venez nous rendre visite en personne",
    "contact.office.map": "Carte du bureau",
    "contact.office.address": "Av. Paulista, 1000 - Luanda, Angola",
    "contact.validation.name.min": "Le nom doit contenir au moins 2 caractères",
    "contact.validation.email.invalid": "Email invalide",
    "contact.validation.subject.required": "Sélectionnez un sujet",
    "contact.validation.message.min": "Le message doit contenir au moins 10 caractères",
    "contact.toast.success": "Message envoyé avec succès!",
    "contact.toast.description": "Nous vous répondrons bientôt.",

    // Home Page - Pricing Section
    "home.pricing.badge": "Tarifs",
    "home.pricing.title": "Plans pour chaque cabinet",
    "home.pricing.subtitle": "Choisissez le plan idéal pour votre entreprise",
    "home.pricing.monthly": "Mensuel",
    "home.pricing.semester": "Semestriel",
    "home.pricing.annual": "Annuel",
    "home.pricing.save.semester": "-10%",
    "home.pricing.save.annual": "-20%",
    "home.pricing.popular": "Le plus populaire",
    "home.pricing.billed.monthly": "Facturé mensuellement",
    "home.pricing.billed.semester": "Facturé semestriellement",
    "home.pricing.billed.annual": "Facturé annuellement",
    "home.pricing.cta": "Commencer",
    "home.pricing.plan.starter.name": "Starter",
    "home.pricing.plan.starter.description": "Parfait pour les cabinets débutants",
    "home.pricing.plan.professional.name": "Professional",
    "home.pricing.plan.professional.description": "Pour les cabinets en croissance",
    "home.pricing.plan.enterprise.name": "Enterprise",
    "home.pricing.plan.enterprise.description": "Pour les grands cabinets",

    // Pricing Page - Plans Details
    "pricing.plan.starter.name": "Starter",
    "pricing.plan.starter.description": "Parfait pour les cabinets débutants",
    "pricing.plan.professional.name": "Professional",
    "pricing.plan.professional.description": "Pour les cabinets en croissance",
    "pricing.plan.enterprise.name": "Enterprise",
    "pricing.plan.enterprise.description": "Pour les grands cabinets",
    "pricing.feature.users": "Jusqu'à {count} utilisateurs",
    "pricing.feature.users.unlimited": "Utilisateurs illimités",
    "pricing.feature.process.basic": "Gestion de dossiers basique",
    "pricing.feature.process.complete": "Gestion complète de dossiers",
    "pricing.feature.process.all": "Toutes les fonctionnalités Professional",
    "pricing.feature.storage": "{size} de stockage",
    "pricing.feature.storage.unlimited": "Stockage illimité",
    "pricing.feature.support.email": "Support par email",
    "pricing.feature.support.priority": "Support prioritaire 24/7",
    "pricing.feature.support.phone": "Support téléphonique premium",
    "pricing.feature.reports.basic": "Rapports basiques",
    "pricing.feature.reports.advanced": "Rapports avancés",
    "pricing.feature.integrations": "Intégrations API",
    "pricing.feature.integrations.custom": "Intégrations personnalisées",
    "pricing.feature.agenda.simple": "Agenda simple",
    "pricing.feature.agenda.smart": "Agenda intelligent",
    "pricing.feature.documents": "Gestion de documents",
    "pricing.feature.dashboard.basic": "Tableau de bord basique",
    "pricing.feature.dashboard.custom": "Tableau de bord personnalisé",
    "pricing.feature.automation": "Automatisation des tâches",
    "pricing.feature.notifications": "Notifications en temps réel",
    "pricing.feature.finance": "Contrôle financier complet",
    "pricing.feature.backup": "Sauvegarde automatique quotidienne",
    "pricing.feature.manager": "Gestionnaire de compte dédié",
    "pricing.feature.training": "Formation personnalisée",
    "pricing.feature.sla": "SLA garanti 99.9%",
    "pricing.feature.whitelabel": "White-label disponible",
    "pricing.feature.audit": "Audit et conformité",
    "pricing.feature.migration": "Migration de données assistée",
    "pricing.feature.consulting": "Conseil stratégique",
    "pricing.features.multiuser.title": "Multi-utilisateur",
    "pricing.features.multiuser.description": "Gestion d'équipe avec contrôle des permissions",
    "pricing.features.security.title": "Sécurité",
    "pricing.features.security.description": "Cryptage et conformité LGPD",
    "pricing.features.performance.title": "Performance",
    "pricing.features.performance.description": "Système rapide et réactif",
    "pricing.features.storage.title": "Stockage",
    "pricing.features.storage.description": "Cloud sécurisé et évolutif",
    "pricing.features.support.title": "Support",
    "pricing.features.support.description": "Équipe spécialisée toujours disponible",
    "pricing.features.analytics.title": "Analytics",
    "pricing.features.analytics.description": "Rapports et insights avancés",
    "pricing.faq.change_plan": "Puis-je changer de plan à tout moment?",
    "pricing.faq.change_plan.answer": "Oui! Vous pouvez faire une mise à niveau ou une rétrogradation de votre plan à tout moment. Les modifications prennent effet au prochain cycle de facturation.",
    "pricing.faq.trial": "Y a-t-il une période d'essai gratuite?",
    "pricing.faq.trial.answer": "Oui, nous offrons 14 jours d'essai gratuit sur tous les plans, sans carte de crédit requise.",
    "pricing.faq.cancel": "Comment fonctionne l'annulation?",
    "pricing.faq.cancel.answer": "Vous pouvez annuler votre abonnement à tout moment sans pénalités ni frais supplémentaires. Vos données restent disponibles pendant 30 jours après l'annulation.",
    "pricing.faq.ngo": "Offrez-vous des réductions pour les ONG?",
    "pricing.faq.ngo.answer": "Oui! Nous offrons des réductions spéciales pour les organisations à but non lucratif. Contactez notre équipe commerciale.",
    "pricing.faq.support_included": "Les prix incluent-ils le support technique?",
    "pricing.faq.support_included.answer": "Oui, tous les plans incluent le support technique. Le niveau de support varie selon le plan choisi.",
    "pricing.faq.setup_fee": "Y a-t-il des frais de configuration ou d'installation?",
    "pricing.faq.setup_fee.answer": "Non, nous ne facturons aucun frais de configuration. Vous ne payez que les frais mensuels du plan choisi.",
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.pricing": "Precios",
    "nav.docs": "Documentación",
    "nav.contact": "Contacto",
    "nav.login": "Iniciar Sesión",
    "nav.register": "Comenzar",
    
    // Hero Section
    "hero.badge": "Plataforma líder en gestión jurídica",
    "hero.title": "El futuro de la gestión jurídica está aquí",
    "hero.subtitle": "Transforme su despacho con la plataforma más completa e intuitiva del mercado. Gestión de procesos, clientes y finanzas en un solo lugar.",
    "hero.cta.primary": "Comenzar ahora gratis",
    "hero.cta.secondary": "Programar demostración",
    "hero.feature.no_card": "Sin tarjeta de crédito",
    "hero.feature.trial": "14 días gratis",
    "hero.feature.cancel": "Cancela cuando quieras",
    
    // Stats
    "stats.offices": "Despachos activos",
    "stats.cases": "Casos gestionados",
    "stats.satisfaction": "Satisfacción del cliente",
    "stats.productivity": "Aumento de productividad",
    
    // Features
    "features.badge": "Características",
    "features.title": "Todo lo que necesitas en un solo lugar",
    "features.subtitle": "Características poderosas para optimizar cada aspecto de tu práctica jurídica",
    
    // Pricing
    "pricing.badge": "Precios",
    "pricing.title": "Planes para cada despacho",
    "pricing.subtitle": "Elige el plan ideal para tu negocio",
    "pricing.monthly": "Mensual",
    "pricing.semester": "Semestral",
    "pricing.annual": "Anual",
    "pricing.per_month": "/mes",
    "pricing.billed_monthly": "Facturado mensualmente",
    "pricing.billed_semester": "Facturado semestralmente",
    "pricing.billed_annual": "Facturado anualmente",
    "pricing.cta": "Comenzar",
    
    // Testimonials
    "testimonials.badge": "Testimonios",
    "testimonials.title": "Lo que dicen nuestros clientes",
    "testimonials.subtitle": "Despachos de todo Brasil confían en Kamaia",
    
    // CTA
    "cta.title": "¿Listo para transformar tu despacho?",
    "cta.subtitle": "Únete a cientos de despachos que ya han modernizado su gestión jurídica",
    "cta.primary": "Comenzar prueba gratuita",
    "cta.secondary": "Hablar con ventas",
    
    // Footer
    "footer.product": "Producto",
    "footer.company": "Empresa",
    "footer.resources": "Recursos",
    "footer.legal": "Legal",
    "footer.newsletter": "Recibir novedades",
    "footer.newsletter.placeholder": "tu@email.com",
    "footer.newsletter.cta": "Suscribirse",
    "footer.rights": "Todos los derechos reservados.",
    
    // Auth - Login
    "auth.login.title": "Accede a tu cuenta",
    "auth.login.subtitle": "Ingresa tus credenciales para acceder al sistema",
    "auth.login.email": "Email",
    "auth.login.email.placeholder": "tu@email.com",
    "auth.login.password": "Contraseña",
    "auth.login.password.placeholder": "********",
    "auth.login.forgot": "¿Olvidaste tu contraseña?",
    "auth.login.submit": "Iniciar Sesión",
    "auth.login.no_account": "¿No tienes cuenta?",
    "auth.login.contact": "Contáctanos",
    
    // Auth - Register
    "auth.register.title": "Crear una cuenta",
    "auth.register.subtitle": "Completa tus datos para registrarte",
    "auth.register.name": "Nombre completo",
    "auth.register.name.placeholder": "Juan Silva",
    "auth.register.email": "Email",
    "auth.register.email.placeholder": "tu@email.com",
    "auth.register.password": "Contraseña",
    "auth.register.password.placeholder": "********",
    "auth.register.submit": "Crear cuenta",
    "auth.register.has_account": "¿Ya tienes cuenta?",
    "auth.register.login": "Iniciar sesión",
    
    // Auth - Forgot Password
    "auth.forgot.title": "¿Olvidaste tu contraseña?",
    "auth.forgot.subtitle": "Ingresa tu email y te enviaremos un enlace para restablecer tu contraseña",
    "auth.forgot.email": "Email",
    "auth.forgot.email.placeholder": "tu@email.com",
    "auth.forgot.submit": "Enviar enlace de recuperación",
    "auth.forgot.back": "Volver al inicio de sesión",
    "auth.forgot.success": "¡Email enviado!",
    "auth.forgot.success.description": "Verifica tu bandeja de entrada para restablecer tu contraseña.",
    
    // Validation
    "validation.email.invalid": "Por favor, ingresa un email válido.",
    "validation.password.min": "La contraseña debe tener al menos 6 caracteres.",
    "validation.password.max": "La contraseña debe tener como máximo 50 caracteres.",
    "validation.password.uppercase": "La contraseña debe contener al menos una letra mayúscula.",
    "validation.password.lowercase": "La contraseña debe contener al menos una letra minúscula.",
    "validation.password.number": "La contraseña debe contener al menos un número.",
    "validation.name.min": "El nombre debe tener al menos 2 caracteres.",

    // Public Pages - Home
    "home.hero.badge": "Plataforma líder en gestión jurídica",
    "home.hero.title": "El futuro de la gestión jurídica está aquí",
    "home.hero.subtitle": "Transforme su despacho con la plataforma más completa e intuitiva del mercado. Gestión de procesos, clientes y finanzas en un solo lugar.",
    "home.hero.cta.primary": "Comenzar ahora gratis",
    "home.hero.cta.secondary": "Programar demostración",
    "home.hero.trust.badge": "Sin tarjeta de crédito",
    "home.hero.trust.trial": "14 días gratis",
    "home.hero.trust.cancel": "Cancela cuando quieras",
    
    "home.stats.offices": "Despachos activos",
    "home.stats.cases": "Casos gestionados",
    "home.stats.satisfaction": "Satisfacción del cliente",
    "home.stats.productivity": "Aumento de productividad",
    
    "home.features.badge": "Características Poderosas",
    "home.features.title": "Todo lo que necesitas en un solo lugar",
    "home.features.subtitle": "Características poderosas diseñadas específicamente para despachos de abogados modernos",
    
    "home.testimonials.badge": "Testimonios",
    "home.testimonials.title": "Lo que dicen nuestros clientes",
    "home.testimonials.subtitle": "Despachos de toda Angola y el Mundo confían en Kamaia",
    
    "home.cta.title": "¿Listo para transformar tu despacho?",
    "home.cta.subtitle": "Únete a cientos de despachos que ya han modernizado su gestión jurídica",
    "home.cta.primary": "Comenzar prueba gratuita",
    "home.cta.secondary": "Hablar con ventas",

    // Pricing Page
    "pricing.title": "Planes y Precios",
    "pricing.subtitle": "Elige el plan ideal para tu despacho",
    "pricing.monthly": "Mensual",
    "pricing.semester": "Semestral",
    "pricing.annual": "Anual",
    "pricing.per_month": "/mes",
    "pricing.popular": "Más Popular",
    "pricing.cta": "Comenzar",
    "pricing.billed.monthly": "Facturado mensualmente",
    "pricing.billed.semester": "Facturado semestralmente",
    "pricing.billed.annual": "Facturado anualmente",
    "pricing.save": "Ahorra",
    "pricing.per_year": "por año",
    "pricing.users": "usuarios",
    "pricing.included": "Características incluidas:",
    "pricing.custom.title": "¿Necesitas una solución personalizada?",
    "pricing.custom.description": "Para despachos con necesidades específicas, ofrecemos planes personalizados con características exclusivas",
    "pricing.custom.cta": "Hablar con especialista",
    "pricing.custom.docs": "Ver documentación",
    "pricing.features.title": "Características disponibles en todos los planes",
    "pricing.features.subtitle": "Funcionalidades esenciales para tu gestión jurídica",
    "pricing.faq.title": "Preguntas Frecuentes",
    "pricing.faq.subtitle": "Todo lo que necesitas saber sobre nuestros planes",
    "pricing.faq.more": "¿Aún tienes dudas?",
    "pricing.faq.contact": "Contáctanos",

    // Footer
    "footer.description": "La plataforma más completa para gestión de despachos de abogados y departamentos jurídicos.",
    "footer.newsletter.title": "Recibir novedades",
    "footer.newsletter.placeholder": "tu@email.com",
    "footer.newsletter.button": "Suscribirse",
    "footer.product.title": "Producto",
    "footer.company.title": "Empresa",
    "footer.resources.title": "Recursos",
    "footer.legal.title": "Legal",
    "footer.contact.email": "Email",
    "footer.contact.phone": "Teléfono",
    "footer.contact.address": "Dirección",
    "footer.copyright": "Todos los derechos reservados.",

    // Contact Page
    "contact.badge": "Contáctanos",
    "contact.title": "Estamos aquí para ayudarte",
    "contact.subtitle": "Habla con nuestro equipo de expertos y descubre cómo Kamaia puede transformar tu despacho",
    "contact.info.email": "Email",
    "contact.info.email.value": "contacto@kamaia.com",
    "contact.info.email.description": "Respuesta en 24 horas",
    "contact.info.phone": "Teléfono",
    "contact.info.phone.value": "+244 949 273 453",
    "contact.info.phone.description": "Lun-Vie, 9h a 18h",
    "contact.info.address": "Dirección",
    "contact.info.address.value": "Luanda, Angola",
    "contact.info.address.description": "Av. Paulista, 1000",
    "contact.info.hours": "Horario",
    "contact.info.hours.value": "Lunes a Viernes",
    "contact.info.hours.description": "9h a 18h (BRT)",
    "contact.form.title": "Envía tu mensaje",
    "contact.form.subtitle": "Completa el formulario a continuación y nos pondremos en contacto pronto",
    "contact.form.name": "Nombre completo",
    "contact.form.name.placeholder": "Juan Silva",
    "contact.form.email": "Email",
    "contact.form.email.placeholder": "juan@ejemplo.com",
    "contact.form.phone": "Teléfono",
    "contact.form.phone.placeholder": "+244 932938932",
    "contact.form.company": "Despacho/Empresa",
    "contact.form.company.placeholder": "Nombre del despacho",
    "contact.form.subject": "Asunto",
    "contact.form.subject.placeholder": "Selecciona un asunto",
    "contact.form.subject.sales": "Ventas y planes",
    "contact.form.subject.demo": "Programar demostración",
    "contact.form.subject.support": "Soporte técnico",
    "contact.form.subject.partnership": "Asociaciones",
    "contact.form.subject.other": "Otro asunto",
    "contact.form.message": "Mensaje",
    "contact.form.message.placeholder": "Cuéntanos cómo podemos ayudarte...",
    "contact.form.submit": "Enviar mensaje",
    "contact.form.success.title": "¡Mensaje Enviado!",
    "contact.form.success.description": "Hemos recibido tu mensaje y nos pondremos en contacto pronto.",
    "contact.reasons.title": "¿Cómo podemos ayudarte?",
    "contact.reasons.product.title": "Dudas sobre el producto",
    "contact.reasons.product.description": "Resuelve tus dudas sobre funcionalidades y recursos",
    "contact.reasons.demo.title": "Programar demostración",
    "contact.reasons.demo.description": "Ve Kamaia en acción con un especialista",
    "contact.reasons.support.title": "Soporte técnico",
    "contact.reasons.support.description": "Ayuda con problemas técnicos o bugs",
    "contact.live.title": "¿Prefieres hablar en vivo?",
    "contact.live.description": "Programa una demostración gratuita y ve Kamaia en acción con uno de nuestros especialistas.",
    "contact.live.cta": "Programar demostración",
    "contact.help.title": "Centro de ayuda",
    "contact.help.description": "Encuentra respuestas rápidas en nuestra base de conocimiento",
    "contact.help.docs": "Documentación completa",
    "contact.help.faq": "Preguntas frecuentes",
    "contact.help.videos": "Tutoriales en vídeo",
    "contact.help.api": "Documentación de la API",
    "contact.office.title": "Nuestra oficina",
    "contact.office.description": "Ven a visitarnos en persona",
    "contact.office.map": "Mapa de la oficina",
    "contact.office.address": "Av. Paulista, 1000 - Luanda, Angola",
    "contact.validation.name.min": "El nombre debe tener al menos 2 caracteres",
    "contact.validation.email.invalid": "Email inválido",
    "contact.validation.subject.required": "Selecciona un asunto",
    "contact.validation.message.min": "El mensaje debe tener al menos 10 caracteres",
    "contact.toast.success": "¡Mensaje enviado con éxito!",
    "contact.toast.description": "Nos pondremos en contacto pronto.",

    // Home Page - Pricing Section
    "home.pricing.badge": "Precios",
    "home.pricing.title": "Planes para cada despacho",
    "home.pricing.subtitle": "Elige el plan ideal para tu negocio",
    "home.pricing.monthly": "Mensual",
    "home.pricing.semester": "Semestral",
    "home.pricing.annual": "Anual",
    "home.pricing.save.semester": "-10%",
    "home.pricing.save.annual": "-20%",
    "home.pricing.popular": "Más popular",
    "home.pricing.billed.monthly": "Facturado mensualmente",
    "home.pricing.billed.semester": "Facturado semestralmente",
    "home.pricing.billed.annual": "Facturado anualmente",
    "home.pricing.cta": "Comenzar",
    "home.pricing.plan.starter.name": "Starter",
    "home.pricing.plan.starter.description": "Perfecto para despachos principiantes",
    "home.pricing.plan.professional.name": "Professional",
    "home.pricing.plan.professional.description": "Para despachos en crecimiento",
    "home.pricing.plan.enterprise.name": "Enterprise",
    "home.pricing.plan.enterprise.description": "Para grandes despachos",

    // Pricing Page - Plans Details
    "pricing.plan.starter.name": "Starter",
    "pricing.plan.starter.description": "Perfecto para despachos principiantes",
    "pricing.plan.professional.name": "Professional",
    "pricing.plan.professional.description": "Para despachos en crecimiento",
    "pricing.plan.enterprise.name": "Enterprise",
    "pricing.plan.enterprise.description": "Para grandes despachos",
    "pricing.feature.users": "Hasta {count} usuarios",
    "pricing.feature.users.unlimited": "Usuarios ilimitados",
    "pricing.feature.process.basic": "Gestión de casos básica",
    "pricing.feature.process.complete": "Gestión completa de casos",
    "pricing.feature.process.all": "Todas las características Professional",
    "pricing.feature.storage": "{size} de almacenamiento",
    "pricing.feature.storage.unlimited": "Almacenamiento ilimitado",
    "pricing.feature.support.email": "Soporte por email",
    "pricing.feature.support.priority": "Soporte prioritario 24/7",
    "pricing.feature.support.phone": "Soporte telefónico premium",
    "pricing.feature.reports.basic": "Informes básicos",
    "pricing.feature.reports.advanced": "Informes avanzados",
    "pricing.feature.integrations": "Integraciones vía API",
    "pricing.feature.integrations.custom": "Integraciones personalizadas",
    "pricing.feature.agenda.simple": "Agenda simple",
    "pricing.feature.agenda.smart": "Agenda inteligente",
    "pricing.feature.documents": "Gestión de documentos",
    "pricing.feature.dashboard.basic": "Dashboard básico",
    "pricing.feature.dashboard.custom": "Dashboard personalizado",
    "pricing.feature.automation": "Automatización de tareas",
    "pricing.feature.notifications": "Notificaciones en tiempo real",
    "pricing.feature.finance": "Control financiero completo",
    "pricing.feature.backup": "Backup automático diario",
    "pricing.feature.manager": "Gerente de cuenta dedicado",
    "pricing.feature.training": "Capacitación personalizada",
    "pricing.feature.sla": "SLA garantizado 99.9%",
    "pricing.feature.whitelabel": "White-label disponible",
    "pricing.feature.audit": "Auditoría y cumplimiento",
    "pricing.feature.migration": "Migración de datos asistida",
    "pricing.feature.consulting": "Consultoría estratégica",
    "pricing.features.multiuser.title": "Multi-usuario",
    "pricing.features.multiuser.description": "Gestión de equipos con control de permisos",
    "pricing.features.security.title": "Seguridad",
    "pricing.features.security.description": "Encriptación y cumplimiento con LGPD",
    "pricing.features.performance.title": "Rendimiento",
    "pricing.features.performance.description": "Sistema rápido y responsive",
    "pricing.features.storage.title": "Almacenamiento",
    "pricing.features.storage.description": "Cloud seguro y escalable",
    "pricing.features.support.title": "Soporte",
    "pricing.features.support.description": "Equipo especializado siempre disponible",
    "pricing.features.analytics.title": "Analytics",
    "pricing.features.analytics.description": "Informes e insights avanzados",
    "pricing.faq.change_plan": "¿Puedo cambiar de plan en cualquier momento?",
    "pricing.faq.change_plan.answer": "¡Sí! Puedes hacer upgrade o downgrade de tu plan en cualquier momento. Los cambios entran en vigor en el próximo ciclo de facturación.",
    "pricing.faq.trial": "¿Existe período de prueba gratuito?",
    "pricing.faq.trial.answer": "Sí, ofrecemos 14 días de prueba gratuita en todos los planes, sin necesidad de tarjeta de crédito.",
    "pricing.faq.cancel": "¿Cómo funciona la cancelación?",
    "pricing.faq.cancel.answer": "Puedes cancelar tu suscripción en cualquier momento sin multas o tarifas adicionales. Tus datos están disponibles durante 30 días después de la cancelación.",
    "pricing.faq.ngo": "¿Ofrecen descuento para ONGs?",
    "pricing.faq.ngo.answer": "¡Sí! Ofrecemos descuentos especiales para organizaciones sin fines de lucro. Contacta con nuestro equipo comercial.",
    "pricing.faq.support_included": "¿Los precios incluyen soporte técnico?",
    "pricing.faq.support_included.answer": "Sí, todos los planes incluyen soporte técnico. El nivel de soporte varía según el plan elegido.",
    "pricing.faq.setup_fee": "¿Hay tarifa de configuración o instalación?",
    "pricing.faq.setup_fee.answer": "No, no cobramos ninguna tarifa de configuración. Solo pagas la mensualidad del plan elegido.",
  }
}
